In [2]:
import numpy as np
a = np.array([2,4,6])
b = np.array([4,5,6])

result = a + b
print(result)

[ 6  9 12]


In [3]:
result1 = a * b
print(result1)

[ 8 20 36]


In [4]:
result2 = a/b
print(result2)

[0.5 0.8 1. ]


In [5]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[1,2,3]])

x = A + B
print(x)

[[ 8 10 12]
 [ 5  7  9]]


In [6]:
y = A - B
print(y)

[[-6 -6 -6]
 [ 3  3  3]]


In [7]:
z = A * B
print(z)

[[ 7 16 27]
 [ 4 10 18]]


In [8]:
h = A / B
print(h)

[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]


In [9]:
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [10]:
A = np.array([[1,2,3],[4,5,6]])
C = np.array([[7,8,9],[1,2,3],[1,2,3]])

m = A.dot(C)
print(m)

[[12 18 24]
 [39 54 69]]


In [11]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[1,2,3]])

s = np.inner(A, B)
print(s)

[[ 50  14]
 [122  32]]


In [12]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[1,2,3]])

s = np.outer(A, B)
print(s)

[[ 7  8  9  1  2  3]
 [14 16 18  2  4  6]
 [21 24 27  3  6  9]
 [28 32 36  4  8 12]
 [35 40 45  5 10 15]
 [42 48 54  6 12 18]]


In [14]:
h, *k  = 10, 20, 30
print(type(k))

<class 'list'>


In [16]:
s = 'amazing'
#print(s.index('a',2,2))
# The result is 'ValueError'

In [17]:
x = [1,2,3]
y = x
y[1]=4
print(x)

[1, 4, 3]


In [20]:
num = set([1,1,2,3,3,4,4])
print(type(num))
print(len(num))

<class 'set'>
4


In [22]:
str = 'allinpython'
#print(str.index('e'))
# ValueError

In [23]:
x = 'abcd'
for i in range(len(x)):
    print(i)

0
1
2
3


In [24]:
str1 = 'awesome'
print(str1.replace('e','r',1))


awrsome


In [25]:
my_str = 'abcde'
print(my_str.split('c'))

['ab', 'de']


In [27]:
L1 = [10,20,30,40]
L1[1] = 50
print(L1)

[10, 50, 30, 40]


In [28]:
a = {'name': 'abc'}
b = a 
c = a.copy()
a['name'] = 'xyz'
print(b['name'], c['name']) 

xyz abc
